- type: autoSalaryConfig
  id: AutoSalaryConfig
  payInterval: 1200

- type: autoSalaryJob
  id: Sheriff
  salary: 17000

- type: autoSalaryJob
  id: FrontierRepresentative
  salary: 20000

- type: autoSalaryJob
  id: OutpostDispatcher
  salary: 13500

- type: autoSalaryJob
  id: MailCarrier
  salary: 8000

- type: autoSalaryJob
  id: AFOfficer
  salary: 11000

- type: autoSalaryJob
  id: Bailiff
  salary: 13500

- type: autoSalaryJob
  id: Lieutenant
  salary: 12000

- type: autoSalaryJob
  id: Ranger
  salary: 10000

- type: autoSalaryJob
  id: Coroner
  salary: 11000

- type: autoSalaryJob
  id: Detective
  salary: 11000

- type: autoSalaryJob
  id: LegalRepresentative
  salary: 15000

- type: autoSalaryJob
  id: Cadet
  salary: 8000

- type: autoSalaryJob
  id: Paramedic
  salary: 10000

- type: autoSalaryJob
  id: MedicalOperationsManager
  salary: 12000

- type: autoSalaryJob
  id: AFEngineer
  salary: 9000

- type: autoSalaryJob
  id: AFDoctor
  salary: 9000

- type: autoSalaryJob
  id: AFWorker
  salary: 9000
