- type: playTimeTracker
  id: Jobsmuggler

- type: playTimeTracker
  id: JobsmugglerBodyguard

- type: playTimeTracker
  id: JobMedSyn

- type: playTimeTracker
  id: JobEngineerSyn

- type: playTimeTracker
  id: JobStormtrooper

- type: playTimeTracker
  id: JobCommander

- type: playTimeTracker
  id: JobparaMedical

- type: playTimeTracker
  id: JobparaMedicalInterview

- type: playTimeTracker
  id: JobOutpostMedic

- type: playTimeTracker
  id: JobOutpostEngineer

- type: playTimeTracker
  id: JobOutpostService

- type: playTimeTracker
  id: JobEngineerNfsd
