- type: job
  id: DirectorOfCare
  name: job-name-doc
  description: job-description-doc
  playTimeTracker: JobDirectorOfCare
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
  whitelisted: true
  startingGear: DocGear
  alwaysUseSpawner: true
  icon: "JobIconDocForge" # Forge-change
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 55 # Second from the top
  canBeAntag: false
  salary: 12000 # Corvax-Forge-Salary
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: MedicalBountyBankPayment # any medical bounties sold go directly into the bank
        account: Medical
      - type: PreventShipyardTitleOverwrite
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DocGear
  equipment:
    pocket1: Hypospray #Forge
    pocket2: ToolboxParamedAdvanced
  storage:
    back:
    - StationAdministrationConsoleFlatpack
    - MobileComputerTabletopCommsFlatpack
    - BoxFolderMedicalDoctor
    - RubberStampDoc
    - MedTekCartridge #Forge
    - NFClothingEyesNightVisionGogglesMed
    - EncryptionKeyHospital # Forge-change

- type: chameleonOutfit
  id: DirectorOfCareChameleonOutfit
  job: DirectorOfCare
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
