# - type: ghostRole
#  id: SyndicateAgentSpySmugger
#  name: ghost-role-information-syndicate-reinforcement-cadet-name
#  description: ghost-role-information-syndicate-reinforcement-cadet-description
#  rules: ghost-role-information-syndicate-reinforcement-rules
#  entityPrototype: MobHumanSyndicateAgentSpy
#  iconPrototype: ClothingMaskGasVoiceChameleon
#  whitelisted: true

# - type: entity
#  parent: MobHumanSyndicateAgent
#  id: MobHumanSyndicateAgentSpySmugger
#  name: syndicate spy
#  components:
#  - type: Loadout
#    prototypes: [SyndicateReinforcementSpySmugger]
#    roleLoadout: [ RoleSurvivalSyndicate ]

- type: job
  id: smugglerBodyguard
  name: forge-job-name-smugglerbodyguard
  description: forge-job-desc-smugglerbodyguard
  playTimeTracker: JobsmugglerBodyguard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobMercenary
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 72000 # 20 hours
  whitelisted: true
  startingGear: SmugglerBodyguardGear
  alwaysUseSpawner: true
  access:
  - SyndicateAgent
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconBodyguardSmuggler"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: SmugglerBodyguardGear
  equipment:
    ears: ClothingHeadsetAltSyndicateSmuggler
    id: SyndiPDACadet
    belt: ClothingBeltSyndieHolster
    mask: ClothingMaskNeckGaiter
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - NFBoxSurvivalExtended
    - ToolboxKadet

- type: chameleonOutfit
  id: SmugglerBodyguardChameleonOutfit
  job: smugglerBodyguard

