- type: job
  id: EngineerSyn
  name: forge-job-name-engineersyn
  description: forge-job-desc-engineersyn
  playTimeTracker: JobEngineerSyn
  access:
  - SyndicateAgent
  - NuclearOperative
  requirements:
    - !type:RoleTimeRequirement
      role: JobStormtrooper
      time: 108000 # 30 hours
    - !type:RoleTimeRequirement
      role: JobEngineerNfsd
      time: 36000 # 10 hours
 # whitelisted: true
  startingGear: EngineerSynGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconEngineerSyn"
  supervisors: job-supervisors-syndicate
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: EngineerSynGear
  equipment:
    ears: ClothingHeadsetAltSyndicateShturm
    id: SyndiPDA
    belt: ClothingBeltMilitaryWebbingSyndicateEng
    mask: ClothingMaskGasSyndicate
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - NFBoxSurvivalExtended
    - SyndicateDataMinerFlatpack
    - FSyndicateProtolatheFlatpack
    - ToolboxEngineerSyn

- type: chameleonOutfit
  id: EngineerSynChameleonOutfit
  job: EngineerSyn
