- type: job
  id: MedSyn
  name: forge-job-name-medsyn
  description: forge-job-desc-medsyn
  playTimeTracker: JobMedSyn
  access:
  - SyndicateAgent
  - NuclearOperative
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
    - !type:RoleTimeRequirement
      role: JobparaMedical
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobBrigmedic
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hours
 # whitelisted: true
  startingGear: MedSynGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconMedSyn"
  supervisors: job-supervisors-syndicate
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: MedSynGear
  equipment:
    ears: ClothingHeadsetAltSyndicateShturm
    id: SyndiPDACParamed
    belt: ClothingBeltMilitaryWebbingMedFilled
    mask: ClothingMaskGasSyndicate
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - NFBoxSurvivalExtended
    - HypoBrigmedic
    - PillCanisterTricordrazine
    - SyndicateDataMinerFlatpack
    - ToolboxMedic

- type: chameleonOutfit
  id: MedSynChameleonOutfit
  job: MedSyn
