- type: job
  id: smuggler
  name: forge-job-name-smuggler
  description: forge-job-desc-smuggler
  playTimeTracker: Jobsmuggler
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
    - !type:RoleTimeRequirement
      role: JobMercenary
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hours
  whitelisted: true
  startingGear: SmugglerGear
  alwaysUseSpawner: true
  access:
  - SyndicateAgent
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconSmuggler"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: SmugglerGear
  equipment:
    ears: ClothingHeadsetAltSyndicateSmuggler
    id: SyndiPDASmugger
    belt: ClothingBeltSyndieHolster
    pocket1: NFWeaponPistolViper
    pocket2: SmuggerUplinkRadio200TC
    mask: ClothingMaskNeckGaiter
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - NFBoxSurvivalExtended
    - RubberStampSyndicate
    - ExchangerSyndicateFlatpack

- type: chameleonOutfit
  id: smugglerChameleonOutfit
  job: smuggler
