- type: department
  id: Syndicate
  name: department-Syndicate
  description: department-Syndicate-description
  color: "#DE3A3A"
  weight: -20 # accounted for in jobs
  roles:
  - Commander
  - MedSyn
  - EngineerSyn
  - Stormtrooper
  - smuggler
  - smugglerBodyguard

- type: department
  id: MedicalDepartment
  primary: false
  name: department-medical
  description: department-medical-description
  color: "#74c3f7"
  weight: -20 # accounted for in jobs
  roles:
  - DirectorOfCare
  - paraMedical
